stages: 
  - test

phpunit_test:
  stage: test
  image: php:8.3
  before_script:
    - apt-get update && apt-get install -y unzip
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
  script:
    - php bin/phpunit --log-junit junit.xml
  artifacts:
    reports:
      junit: junit.xml