vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        robot:
            uri_prefix: /upload/robots
            upload_destination: '%kernel.project_dir%/public/upload/robots'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
