name: PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpunit_test:
    runs-on: ubuntu-latest
    container:
      image: php:8.3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Update System and Install Unzip
        run: |
          apt-get update && apt-get install -y unzip

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install

      - name: Run PHPUnit
        run: php bin/phpunit --log-junit junit.xml

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: junit-report
          path: junit.xml
